settings:
  application:
    enabledp: true
    host: 0.0.0.0
    mode: demo
    name: testApp
    port: 8000
    readtimeout: 10000
    writertimeout: 20000
  database:
    driver: mysql
    source: user:password@tcp(127.0.0.1:3306)/dbname?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  gen:
    dbname: testhhh
    frontpath: ../ui/src
  jwt:
    secret: easy-admin
    timeout: 3600
  logger:
    path: temp/logs
    stdout: ''
    level: trace
    enableddb: true
  queue:
    memory:
      poolSize: 100
  extend:
    amap:
      key: de7a062c984bf828d5d1b3a631a517e4