settings:
  application:
    # dev test prod
    mode: prod
    # 服务器ip，默认使用 0.0.0.0
    host: 176.17.0.1
    # 服务名称
    name: easy-admin
    # 端口号
    port: 8000 # 服务端口号
    readtimeout: 1
    writertimeout: 2
    # 数据权限功能开关
    enabledp: false
    # 时区
    timezone: "Africa/Cairo"
    # 区域
    local: ""
  ssl:
    # https domain
    domain: localhost:8000
    # https enable
    enable: false
    # ssl key
    key: ''
    # ssl pem path
    pem: temp/fullchain.pem
  logger:
    # 日志存放路径
    path: temp/logs
    # 日志输出，file：文件，default：命令行，其他：命令行
    stdout: '' #控制台日志，启用后，不输出到文件
    # 日志等级, trace, debug, info, warn, error, fatal
    level: trace
    # 数据库日志开关
    enableddb: false
  jwt:
    # token 密钥，生产环境时及的修改
    secret: easy-admin
    # token 过期时间 单位：秒
    timeout: 3600
  database:
    # 数据库类型 mysql, sqlite3, postgres, sqlserver
    # sqlserver: sqlserver://用户名:密码@地址?database=数据库名
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: easyadmin:easyadmin123@tcp(176.7.0.2:3306)/easy_admin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
#  databases:
#    'locaohost:8000':
#      driver: mysql
#        # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
#        source: user:password@tcp(127.0.0.1:3306)/dbname?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
#      registers:
#        - sources:
#            - user:password@tcp(127.0.0.1:3306)/dbname?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  gen:
    # 代码生成读取的数据库名称
    dbname: easy_admin
    # 代码生成是使用前端代码存放位置，需要指定到src文件夹，相对路径
    frontpath: ../ui/src
  extend: # 扩展项使用说明
    demo:
      name: data
  cache:
    redis:
      addr: 176.7.0.3:6379
      password: 
      db: 1
    # key存在即可
    memory: '' 
  queue:
    memory:
      poolSize: 100
    redis:
      addr: 176.7.0.3:6379
      password: 
      db: 3
      producer:
        streamMaxLength: 100
        approximateMaxLength: true
      consumer:
        visibilityTimeout: 60
        bufferSize: 100
        concurrency: 10
        blockingTimeout: 5
        reclaimInterval: 1
  locker:
    redis: