version: "3.7"

networks:
  easy-admin-network:
    ipam:
      driver: default
      config:
        - subnet: '176.7.0.0/16'
        
volumes:
  mysql:
  redis:
  
services:
  server:
    image: nicesteven/easy-admin
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      easy-admin-network:
        ipv4_address: 176.7.0.1
    healthcheck:
      test: ["CMD", "curl", "-f", "-X GET", "http://176.7.0.1:8080/api/v1/getinfo"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command:
      /easy-admin server -c=/config/settings.yml

  mysql:
    image: mysql:8.0.21
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - $PWD/mysql_data/:/var/lib/mysql:rw
      - $PWD/mysql_init/:/docker-entrypoint-initdb.d/:rw
      - $PWD/config/:/config/
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      easy-admin-network:
        ipv4_address: 176.7.0.2

  redis:
    image: redis:6.0.6
    container_name: redis
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - redis:/data
    networks:
      easy-admin-network:
        ipv4_address: 176.7.0.3